---
fixtures:
  repositories:
    powershell: https://github.com/puppetlabs/puppetlabs-powershell.git
    registry: https://github.com/puppetlabs/puppetlabs-registry.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
